import '../css/About.css'

const About = () => {
    return (
        <div className="about-container">
            <h1 className="about-title">About This Project</h1>
            <p className="about-description">
                This project is a Data Structure and Algorithm design created by a student from Tongji University, with student ID 2250951.
                It is a part of the Summer 2024 course. The design follows the MIT License.
            </p>
            <p className="about-footer">
                All test data used in this project is generated by AI.
            </p>
        </div>
    );
}

export default About;
