export const data = {
    users: [
        {
            id: 'user1',
            name: 'Alice Johnson',
            location: 'New York City',
            schools: ['PS 101 Brooklyn', 'Stuyvesant High School', 'Columbia University'],
            workplaces: ['Goldman Sachs', 'Google'],
            groups: ['Finance Enthusiasts', 'NYC Tech Meetup'],
            friends: ['user2', 'user3', 'user4', 'user5', 'user6']
        },
        {
            id: 'user2',
            name: 'Bob Smith',
            location: 'San Francisco',
            schools: ['SF Elementary School', 'Lowell High School', 'Stanford University'],
            workplaces: ['Facebook', 'Uber'],
            groups: ['SF Tech Innovators', 'Stanford Alumni'],
            friends: ['user1', 'user3', 'user4', 'user5', 'user6']
        },
        {
            id: 'user3',
            name: 'Charlie Brown',
            location: 'Chicago',
            schools: ['Chicago Public School 52', 'Whitney Young High School', 'University of Chicago'],
            workplaces: ['McKinsey & Company', 'Tesla'],
            groups: ['Chicago Business Network', 'EV Enthusiasts'],
            friends: ['user1', 'user2', 'user4', 'user5', 'user6', 'user7']
        },
        {
            id: 'user4',
            name: 'David Lee',
            location: 'Los Angeles',
            schools: ['LA Elementary', 'Harvard-Westlake School', 'UCLA'],
            workplaces: ['SpaceX', 'Netflix'],
            groups: ['LA Tech Circle', 'Film & Media Group'],
            friends: ['user1', 'user2', 'user3', 'user5', 'user6', 'user7']
        },
        {
            id: 'user5',
            name: 'Eve Carter',
            location: 'Seattle',
            schools: ['Seattle Public School 3', 'Garfield High School', 'University of Washington'],
            workplaces: ['Amazon', 'Microsoft'],
            groups: ['Seattle AI Hub', 'Women in Tech'],
            friends: ['user1', 'user2', 'user3', 'user4', 'user6', 'user7', 'user8']
        },
        {
            id: 'user6',
            name: 'Frank Wright',
            location: 'Boston',
            schools: ['Boston Latin School', 'MIT'],
            workplaces: ['Boston Dynamics', 'HubSpot'],
            groups: ['Boston Robotics Club', 'MIT Alumni'],
            friends: ['user1', 'user2', 'user3', 'user4', 'user5', 'user7', 'user8']
        },
        {
            id: 'user7',
            name: 'Grace Kim',
            location: 'Houston',
            schools: ['Houston Elementary', 'DeBakey High School', 'Rice University'],
            workplaces: ['ExxonMobil', 'NASA'],
            groups: ['Houston Space Enthusiasts', 'Energy Sector Group'],
            friends: ['user3', 'user4', 'user5', 'user6', 'user8', 'user9']
        },
        {
            id: 'user8',
            name: 'Henry Thompson',
            location: 'Miami',
            schools: ['Miami Springs High School', 'University of Miami'],
            workplaces: ['Carnival Cruise Line', 'American Airlines'],
            groups: ['Miami Business Club', 'Travel & Leisure Group'],
            friends: ['user5', 'user6', 'user7', 'user9', 'user10']
        },
        {
            id: 'user9',
            name: 'Isabella Ramirez',
            location: 'Dallas',
            schools: ['Dallas High School', 'Southern Methodist University'],
            workplaces: ['AT&T', 'Southwest Airlines'],
            groups: ['Dallas Innovators', 'Women in Business'],
            friends: ['user7', 'user8', 'user10', 'user11', 'user12']
        },
        {
            id: 'user10',
            name: 'Jack Wilson',
            location: 'San Diego',
            schools: ['San Diego High School', 'UC San Diego'],
            workplaces: ['Qualcomm', 'Intuit'],
            groups: ['San Diego Tech Group', 'Financial Analysts Network'],
            friends: ['user8', 'user9', 'user11', 'user12', 'user13']
        },
        {
            id: 'user11',
            name: 'Karen Mitchell',
            location: 'Austin',
            schools: ['Austin High School', 'University of Texas at Austin'],
            workplaces: ['Dell', 'Whole Foods'],
            groups: ['Austin Startups', 'Health & Wellness'],
            friends: ['user9', 'user10', 'user12', 'user13', 'user14']
        },
        {
            id: 'user12',
            name: 'Larry Hall',
            location: 'Denver',
            schools: ['Denver South High School', 'University of Colorado Boulder'],
            workplaces: ['Coors Brewing Company', 'Dish Network'],
            groups: ['Denver Outdoors Club', 'Tech Entrepreneurs'],
            friends: ['user9', 'user10', 'user11', 'user13', 'user14']
        },
        {
            id: 'user13',
            name: 'Michelle Taylor',
            location: 'Phoenix',
            schools: ['Phoenix Union High School', 'Arizona State University'],
            workplaces: ['Honeywell', 'Banner Health'],
            groups: ['Phoenix Tech Meetup', 'Healthcare Professionals'],
            friends: ['user10', 'user11', 'user12', 'user14', 'user15']
        },
        {
            id: 'user14',
            name: 'Nathan Edwards',
            location: 'Philadelphia',
            schools: ['Central High School', 'University of Pennsylvania'],
            workplaces: ['Comcast', 'Aramark'],
            groups: ['Philly Entrepreneurs', 'Food Industry Network'],
            friends: ['user11', 'user12', 'user13', 'user15', 'user16']
        },
        {
            id: 'user15',
            name: 'Olivia Clark',
            location: 'Detroit',
            schools: ['Detroit High School', 'Wayne State University'],
            workplaces: ['General Motors', 'Ford Motor Company'],
            groups: ['Detroit Auto Enthusiasts', 'Manufacturing Innovators'],
            friends: ['user13', 'user14', 'user16', 'user17', 'user18']
        },
        {
            id: 'user16',
            name: 'Peter Rodriguez',
            location: 'Atlanta',
            schools: ['Grady High School', 'Georgia Tech'],
            workplaces: ['Coca-Cola', 'Delta Air Lines'],
            groups: ['Atlanta Business Club', 'Tech in the South'],
            friends: ['user14', 'user15', 'user17', 'user18', 'user19']
        },
        {
            id: 'user17',
            name: 'Quincy Harris',
            location: 'Portland',
            schools: ['Portland High School', 'University of Oregon'],
            workplaces: ['Nike', 'Intel'],
            groups: ['Portland Startups', 'Tech for Good'],
            friends: ['user15', 'user16', 'user18', 'user19', 'user20']
        },
        {
            id: 'user18',
            name: 'Rebecca Walker',
            location: 'San Antonio',
            schools: ['San Antonio High School', 'Trinity University'],
            workplaces: ['USAA', 'Rackspace'],
            groups: ['San Antonio Tech Network', 'Cybersecurity Group'],
            friends: ['user15', 'user16', 'user17', 'user19', 'user20']
        },
        {
            id: 'user19',
            name: 'Steve Green',
            location: 'Charlotte',
            schools: ['Charlotte High School', 'University of North Carolina at Charlotte'],
            workplaces: ['Bank of America', 'Lowe’s'],
            groups: ['Charlotte Fintech', 'Tech for Good'],
            friends: ['user16', 'user17', 'user18', 'user20']
        },
        {
            id: 'user20',
            name: 'Tina Adams',
            location: 'Las Vegas',
            schools: ['Las Vegas High School', 'University of Nevada, Las Vegas'],
            workplaces: ['MGM Resorts', 'Caesars Entertainment'],
            groups: ['Vegas Entrepreneurs', 'Hospitality Network'],
            friends: ['user17', 'user19', 'user18', 'user13']
        }
    ],
    groups: {
        'Finance Enthusiasts': ['user1', 'user10', 'user2', 'user11'],
        'NYC Tech Meetup': ['user1', 'user6', 'user12'],
        'SF Tech Innovators': ['user2', 'user7', 'user13'],
        'Stanford Alumni': ['user2', 'user3', 'user14'],
        'Chicago Business Network': ['user3', 'user8', 'user15'],
        'EV Enthusiasts': ['user3', 'user9', 'user16'],
        'LA Tech Circle': ['user4', 'user6', 'user12'],
        'Film & Media Group': ['user4', 'user7', 'user17'],
        'Seattle AI Hub': ['user5', 'user10', 'user20'],
        'Women in Tech': ['user5', 'user9', 'user18'],
        'Boston Robotics Club': ['user6', 'user8', 'user20'],
        'MIT Alumni': ['user6', 'user7', 'user16'],
        'Houston Space Enthusiasts': ['user7', 'user9', 'user19'],
        'Energy Sector Group': ['user7', 'user10', 'user20'],
        'Miami Business Club': ['user8', 'user9', 'user14'],
        'Travel & Leisure Group': ['user8', 'user10', 'user15'],
        'Dallas Innovators': ['user9', 'user10', 'user16'],
        'Women in Business': ['user9', 'user10', 'user19'],
        'San Diego Tech Group': ['user10', 'user6', 'user11'],
        'Financial Analysts Network': ['user10', 'user1', 'user17'],
        'Denver Outdoors Club': ['user12', 'user17', 'user18'],
        'Tech Entrepreneurs': ['user12', 'user14', 'user19'],
        'Phoenix Tech Meetup': ['user13', 'user16', 'user17'],
        'Healthcare Professionals': ['user13', 'user15', 'user20'],
        'Philly Entrepreneurs': ['user14', 'user16', 'user18'],
        'Food Industry Network': ['user14', 'user15', 'user19'],
        'Detroit Auto Enthusiasts': ['user15', 'user17', 'user18'],
        'Manufacturing Innovators': ['user15', 'user16', 'user20'],
        'Atlanta Business Club': ['user16', 'user18', 'user19'],
        'Tech in the South': ['user16', 'user15', 'user20'],
        'Portland Startups': ['user17', 'user14', 'user19'],
        'Tech for Good': ['user17', 'user18', 'user13'],
        'San Antonio Tech Network': ['user18', 'user16', 'user15'],
        'Cybersecurity Group': ['user18', 'user17', 'user19'],
        'Charlotte Fintech': ['user19', 'user14', 'user20'],
        'Renewable Energy Network': ['user19', 'user18', 'user13'],
        'Vegas Entrepreneurs': ['user20', 'user14', 'user16'],
        'Hospitality Network': ['user20', 'user13', 'user18']
    },
    friendships: {
        'user1-user2': { id: 'friendship1', users: ['user1', 'user2'] },
        'user1-user3': { id: 'friendship2', users: ['user1', 'user3'] },
        'user1-user4': { id: 'friendship3', users: ['user1', 'user4'] },
        'user1-user5': { id: 'friendship4', users: ['user1', 'user5'] },
        'user1-user6': { id: 'friendship5', users: ['user1', 'user6'] },
        'user2-user3': { id: 'friendship6', users: ['user2', 'user3'] },
        'user2-user4': { id: 'friendship7', users: ['user2', 'user4'] },
        'user2-user5': { id: 'friendship8', users: ['user2', 'user5'] },
        'user2-user6': { id: 'friendship9', users: ['user2', 'user6'] },
        'user3-user4': { id: 'friendship10', users: ['user3', 'user4'] },
        'user3-user5': { id: 'friendship11', users: ['user3', 'user5'] },
        'user3-user6': { id: 'friendship12', users: ['user3', 'user6'] },
        'user3-user7': { id: 'friendship13', users: ['user3', 'user7'] },
        'user4-user5': { id: 'friendship14', users: ['user4', 'user5'] },
        'user4-user6': { id: 'friendship15', users: ['user4', 'user6'] },
        'user4-user7': { id: 'friendship16', users: ['user4', 'user7'] },
        'user5-user6': { id: 'friendship17', users: ['user5', 'user6'] },
        'user5-user7': { id: 'friendship18', users: ['user5', 'user7'] },
        'user5-user8': { id: 'friendship19', users: ['user5', 'user8'] },
        'user6-user7': { id: 'friendship20', users: ['user6', 'user7'] },
        'user6-user8': { id: 'friendship21', users: ['user6', 'user8'] },
        'user7-user8': { id: 'friendship22', users: ['user7', 'user8'] },
        'user7-user9': { id: 'friendship23', users: ['user7', 'user9'] },
        'user8-user9': { id: 'friendship24', users: ['user8', 'user9'] },
        'user8-user10': { id: 'friendship25', users: ['user8', 'user10'] },
        'user9-user10': { id: 'friendship26', users: ['user9', 'user10'] },
        'user9-user11': { id: 'friendship27', users: ['user9', 'user11'] },
        'user10-user11': { id: 'friendship28', users: ['user10', 'user11'] },
        'user11-user12': { id: 'friendship29', users: ['user11', 'user12'] },
        'user11-user13': { id: 'friendship30', users: ['user11', 'user13'] },
        'user12-user13': { id: 'friendship31', users: ['user12', 'user13'] },
        'user12-user14': { id: 'friendship32', users: ['user12', 'user14'] },
        'user13-user14': { id: 'friendship33', users: ['user13', 'user14'] },
        'user13-user15': { id: 'friendship34', users: ['user13', 'user15'] },
        'user14-user15': { id: 'friendship35', users: ['user14', 'user15'] },
        'user14-user16': { id: 'friendship36', users: ['user14', 'user16'] },
        'user15-user16': { id: 'friendship37', users: ['user15', 'user16'] },
        'user15-user17': { id: 'friendship38', users: ['user15', 'user17'] },
        'user16-user17': { id: 'friendship39', users: ['user16', 'user17'] },
        'user16-user18': { id: 'friendship40', users: ['user16', 'user18'] },
        'user17-user18': { id: 'friendship41', users: ['user17', 'user18'] },
        'user17-user19': { id: 'friendship42', users: ['user17', 'user19'] },
        'user18-user19': { id: 'friendship43', users: ['user18', 'user19'] },
        'user18-user20': { id: 'friendship44', users: ['user18', 'user20'] },
        'user19-user20': { id: 'friendship45', users: ['user19', 'user20'] }
    }
};

